DefaultHealth: 16.0
HealthLostOnDeath: 2.0
HealthGainedOnKill: 2.0
LoseLifeIfNotKilledByPlayer: true
MaxHealth: 40.0 # -1 to disable
MaxHealthMessage: '&eYou are already on maximum health'
SpectatorOn0Lives: true # if false bans them for 6 hours
BanMessage: 'Banned for 6 hours by LifeStealPlugin'
HeartRecipe:
  Slot0: DIAMOND_BLOCK
  Slot1: OBSIDIAN
  Slot2: DIAMOND_BLOCK
  Slot3: GOLD_BLOCK
  Slot4: NETHERITE_INGOT
  Slot5: GOLD_BLOCK
  Slot6: DIAMOND_BLOCK
  Slot7: OBSIDIAN
  Slot8: DIAMOND_BLOCK
HeartName: '&cHeart'
HeartLore:
  - '&4Created Using The Riches of 1000 Men'
  - '&4Grants an Extra Heart... Use Wisely'